* removed generated file * get -lATB from ${top_builddir}/aterm instead of ATerm-pkg
* Note that the tcltk-adapter has "bitrot", it doesn't compile/link with the
  new tk anyway: tcltk-adapter.c:564: undefined reference to `Tk_MainEx'